#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ENGINE_ROOT = path.join(__dirname, '..');
const DEFAULT_BOOTCAMP = 'Z:/Threshold training bootcamp';

function loadBootcampConfig() {
    const engineCfg = path.join(ENGINE_ROOT, 'config', 'bootcamp.json');
    const zCfg = path.join('Z:', 'Threshold training bootcamp', 'config', 'bootcamp.json');
    let cfg = { root: DEFAULT_BOOTCAMP, engineRepo: ENGINE_ROOT.replace(/\\/g, '/') };
    if (fs.existsSync(engineCfg)) {
        cfg = { ...cfg, ...JSON.parse(fs.readFileSync(engineCfg, 'utf8')) };
    }
    if (fs.existsSync(zCfg)) {
        const z = JSON.parse(fs.readFileSync(zCfg, 'utf8'));
        cfg = { ...cfg, ...z, root: z.root || cfg.root };
    }
    return normalizeCfg(cfg);
}

function normalizeCfg(cfg) {
    const root = path.resolve((cfg.root || DEFAULT_BOOTCAMP).replace(/\//g, path.sep));
    return { ...cfg, root, engineRepo: cfg.engineRepo || ENGINE_ROOT.replace(/\\/g, '/') };
}

function bootcampPath(cfg, rel) {
    return path.join(cfg.root, rel.replace(/\//g, path.sep));
}

function readJsonl(filePath) {
    if (!fs.existsSync(filePath)) return [];
    return fs.readFileSync(filePath, 'utf8')
        .split('\n')
        .map((l) => l.trim())
        .filter(Boolean)
        .map((l) => JSON.parse(l));
}

const SYSTEM_PROMPTS = {
    small: `You are Threshold Engine — small-task assistant (NPC dialogue, intent routing).
Reply briefly. NPC: 1-3 sentences in character, optional [ACTION: ...].
Classify: one line INTENT + API when asked.`,
    medium: `You are Threshold Engine Dev Agent (medium tasks). Return ONLY executable JavaScript.
Fix minimal diffs for patches. Use World.createObject, PlayerController, Physics, THREE.
Never World.clearWorld() unless asked. Textures: GIMP + textures:watch — not LLM.`,
    large: `You are Threshold Engine architect (large tasks). Return ONLY a complete JavaScript IIFE.
Extend the live scene with World.createObject, PlayerController, Physics.
Never World.clearWorld() unless explicitly requested.`,
};

const TIER_PARAMS = {
    small: { temperature: 0.5, num_predict: 128 },
    medium: { temperature: 0.35, num_predict: 1024 },
    large: { temperature: 0.4, num_predict: 2048 },
};

function escapeSystem(text) {
    return String(text).replace(/"""/g, '\\"\\"\\"');
}

function messagesToModelfileBlocks(entries) {
    const lines = [];
    entries.forEach((row) => {
        const msgs = row.messages || [];
        msgs.forEach((m) => {
            const role = m.role === 'assistant' ? 'assistant' : 'user';
            const content = String(m.content || '').trim();
            if (!content.includes('\n') && content.length < 120 && !content.includes('"""')) {
                lines.push(`MESSAGE ${role} ${content}`);
            } else {
                lines.push(`MESSAGE ${role} """`);
                lines.push(content);
                lines.push('"""');
            }
        });
    });
    return lines;
}

function buildModelfile(tier, modelCfg, entries) {
    const params = TIER_PARAMS[tier] || TIER_PARAMS.medium;
    const lines = [
        `# Generated by npm run bootcamp:build — ${new Date().toISOString()}`,
        `# Tier: ${tier} · Examples: ${entries.length}`,
        `FROM ${modelCfg.base}`,
        '',
        `PARAMETER temperature ${params.temperature}`,
        `PARAMETER num_predict ${params.num_predict}`,
        '',
        `SYSTEM """${escapeSystem(SYSTEM_PROMPTS[tier])}"""`,
        '',
        ...messagesToModelfileBlocks(entries),
        '',
    ];
    return lines.join('\n');
}

function ensureDirs(cfg) {
    const dirs = [
        'config', 'datasets/small', 'datasets/medium', 'datasets/large', 'datasets/raw',
        'modelfiles', 'builds', 'logs', 'scripts',
    ];
    dirs.forEach((d) => fs.mkdirSync(bootcampPath(cfg, d), { recursive: true }));
}

module.exports = {
    ENGINE_ROOT,
    DEFAULT_BOOTCAMP,
    loadBootcampConfig,
    bootcampPath,
    readJsonl,
    buildModelfile,
    ensureDirs,
    SYSTEM_PROMPTS,
};